---
kind: Service
apiVersion: v1
metadata:
  name: hugofs-frontend
spec:
  type: NodePort
  selector:
    app: hugofs-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
---
kind: Service
apiVersion: v1
metadata:
  name: hugofs-backend
spec:
  type: NodePort
  selector:
    app: hugofs-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugofs-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugofs-backend
  template:
    metadata:
      labels:
        app: hugofs-backend
    spec:
      containers:
      - name: hugofs-backend
        image: hugo19941994/hugofs-backend
        ports:
        - containerPort: 3060
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugofs-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugofs-frontend
  template:
    metadata:
      labels:
        app: hugofs-frontend
    spec:
      containers:
      - name: hugofs-frontend
        image: hugo19941994/hugofs-frontend
        ports:
        - containerPort: 4000
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugofs-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - hfs.dev
    secretName: hugofs-tls
  rules:
  - host: hfs.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hugofs-frontend
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: hugofs-backend
            port:
              number: 80
