language: node_js
node_js:
  - node
before_script:
  - npm install
script:
  - npm run lint
  - npm run build:ssr
addons:
  ssh_known_hosts: hugofs.com
before_install:
  - openssl aes-256-cbc -K $encrypted_d9ee3ecfb806_key -iv $encrypted_d9ee3ecfb806_iv -in .travis-deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: .travis-deploy/deploy.sh
  on:
    branch: master
