apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hugofs-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - hfs.dev
    secretName: hugofs-tls
  rules:
  - host: hfs.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: hugofs-frontend
          servicePort: 80
      - path: /api/
        backend:
          serviceName: hugofs-backend
          servicePort: 80
