kind: Service
apiVersion: v1
metadata:
  name: hugofs-backend
spec:
  type: NodePort
  selector:
    app: hugofs-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3060
