kind: Service
apiVersion: v1
metadata:
  name: hugofs-frontend
spec:
  type: NodePort
  selector:
    app: hugofs-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
