apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugofs-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hfs.dev
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
# tls:
# - hosts:
#   - hfs.dev
#   secretName: hugofs-tls
  rules:
  - host: hfs.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hugofs-frontend
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: hugofs-backend
            port:
              number: 80

