apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugofs-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - hfs.dev
    secretName: hugofs-tls
  rules:
  - host: hfs.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hugofs-frontend
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: hugofs-backend
            port:
              number: 80

