name: continuous-delivery

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Save commit SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: hugo19941994
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        platforms: linux/amd64,linux/arm64
        file: ./frontend/Dockerfile
        tags: |
          hugo19941994/hugofs-frontend:${{ steps.vars.outputs.sha_short }}
          hugo19941994/hugofs-frontend:latest
        push: true

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Save commit SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: hugo19941994
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        platforms: linux/amd64,linux/arm64
        file: ./backend/Dockerfile
        tags: |
          hugo19941994/hugofs-backend:${{ steps.vars.outputs.sha_short }}
          hugo19941994/hugofs-backend:latest
        push: true

    - name: Send Telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Deployed new version of HugoFS to https://hfs.dev (${{ steps.vars.outputs.sha_short }})
