name: continuous-delivery

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: hugo19941994
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        tags: hugo19941994/hugofs-frontend:$(git rev-parse --short "$GITHUB_SHA")
        push: true

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: hugo19941994
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        tags: hugo19941994/hugofs-backend:$(git rev-parse --short "$GITHUB_SHA")
        push: true

  deployment:
    name: Deploy to kubernetes cluster
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set k8s context
      uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }}
        k8s-secret: $${{ secrets.K8S_TOKEN }}
      id: setcontext

    - name: Deploy to k8s
      uses: Azure/k8s-deploy@v1.4
      with:
        namespace: 'default'
        manifests: |
            ./.github/manifest.yaml
        kubectl-version: 'latest'

    - name: Deploy to k8s
      run: helm install hugofs .github/hugofs-chart --set image.tag=$(git rev-parse --short "$GITHUB_SHA")

    - name: Send Telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Deployed new version of HugoFS to https://hfs.dev
