name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: The ${{ github.event_name }} event triggered first step.
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test backend
      run: |
        npm --prefix backend ci
        #npm --prefix backend run lint
      env:
        CI: true
    - name: npm install, build, and test frontend
      run: |
        npm --prefix frontend ci
        npm --prefix frontend run lint
      env:
        CI: true
