name: Frontend Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send Telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Attempting deployment of frontend ${{ github.event_name }}.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: hugo19941994
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        tags: hugo19941994/hugofs-frontend:latest
        push: true

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save k8s-1-18-6-do-0-lon1-1595844489030

    - name: Deploy to DigitalOcean Kubernetes (apply manifest)
      run: kubectl apply -f manifest.yaml

    - name: Deploy to DigitalOcean Kubernetes (apply issuer)
      run: kubectl apply -f issuer.yaml

    - name: Deploy to DigitalOcean Kubernetes (apply ingress)
      run: kubectl apply -f ingress.yaml

    - name: Deploy to DigitalOcean Kubernetes (rollout restart frontend deployment)
      run: kubectl rollout restart deployment/hugofs-frontend

    - name: Verify deployment
      run: kubectl rollout status deployment/hugofs-frontend
